### ISSUE TITLE
Response size

### ISSUE THREAD

**Issue by jaikishantulswani** [unstabl3/recce#1]
Hi @unstabl3 It would be better if you add `Page Response Size` along with status code

**Comment by unstabl3** [comment]
Hi, @jaikishantulswani Thank you for suggesting. I will add this in the next release of recce.

**Comment by jaikishantulswani** [comment]
Hi @unstabl3 I think response length switch is ignored

**Comment by unstabl3** [comment]
hi, response length only works with -s option.. hit me up on twitter if you
face more issues. i don't check mails daily.
